on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run linter
      shell: 'script -q -e -c "bash {0}"'
      run: make lint

    - name: Run tests
      shell: 'script -q -e -c "bash {0}"'
      run: make test
